/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form FrmAvanzado
     */
    public FrmAvanzado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAdivinanza = new javax.swing.JTextField();
        btnResultadosA = new javax.swing.JButton();
        jlbPalabra1 = new javax.swing.JLabel();
        jlbPalabra2 = new javax.swing.JLabel();
        jlbPalabra3 = new javax.swing.JLabel();
        txtAdivinanza1 = new javax.swing.JTextField();
        txtAdivinanza3 = new javax.swing.JTextField();
        txtAdivinanza2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jlbAciertos = new javax.swing.JLabel();
        jlbfallas = new javax.swing.JLabel();
        jlbintentos = new javax.swing.JLabel();
        jlbAciertos1 = new javax.swing.JLabel();
        jlbfallas1 = new javax.swing.JLabel();
        jlbintentos1 = new javax.swing.JLabel();
        jlbAciertos2 = new javax.swing.JLabel();
        jlbfallas2 = new javax.swing.JLabel();
        jlbintentos2 = new javax.swing.JLabel();
        jlbAciertos3 = new javax.swing.JLabel();
        jlbfallas3 = new javax.swing.JLabel();
        jlbintentos3 = new javax.swing.JLabel();
        btnIniciar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Adivine el numero entre 0 y 15 ");

        txtAdivinanza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdivinanzaKeyTyped(evt);
            }
        });

        btnResultadosA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados-de-la-votacion.png"))); // NOI18N
        btnResultadosA.setText("Resultados");
        btnResultadosA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosAActionPerformed(evt);
            }
        });

        jlbPalabra1.setText("Palabra1");

        jlbPalabra2.setText("Palabra2");

        jlbPalabra3.setText("Palabra3");

        jLabel5.setText("Tiene 3 intentos");

        jLabel6.setText("Traducir la palabra al idioma Español");

        jLabel11.setText("Aciertos");

        jLabel12.setText("fallas");

        jLabel13.setText("intentos");

        jlbAciertos.setText("0");

        jlbfallas.setText("0");

        jlbintentos.setText("0");

        jlbAciertos1.setText("0");

        jlbfallas1.setText("0");

        jlbintentos1.setText("0");

        jlbAciertos2.setText("0");

        jlbfallas2.setText("0");

        jlbintentos2.setText("0");

        jlbAciertos3.setText("0");

        jlbfallas3.setText("0");

        jlbintentos3.setText("0");

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comienzo.png"))); // NOI18N
        btnIniciar.setText("Empezar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbPalabra2)
                            .addComponent(jlbPalabra1)
                            .addComponent(jlbPalabra3))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdivinanza2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdivinanza1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAdivinanza3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAdivinanza, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbAciertos)
                            .addComponent(jlbAciertos1)
                            .addComponent(jlbAciertos2)
                            .addComponent(jlbAciertos3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbfallas)
                                        .addGap(28, 28, 28)
                                        .addComponent(jlbintentos))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbfallas1)
                                        .addGap(28, 28, 28)
                                        .addComponent(jlbintentos1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbfallas2)
                                        .addGap(28, 28, 28)
                                        .addComponent(jlbintentos2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlbfallas3)
                                        .addGap(28, 28, 28)
                                        .addComponent(jlbintentos3)))))
                        .addGap(47, 47, 47))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciar)
                .addGap(18, 18, 18)
                .addComponent(btnResultadosA)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdivinanza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jlbfallas)
                    .addComponent(jlbAciertos)
                    .addComponent(jlbintentos))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPalabra1)
                    .addComponent(txtAdivinanza1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbfallas1)
                    .addComponent(jlbAciertos1)
                    .addComponent(jlbintentos1))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPalabra2)
                    .addComponent(txtAdivinanza2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbfallas2)
                    .addComponent(jlbAciertos2)
                    .addComponent(jlbintentos2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPalabra3)
                    .addComponent(txtAdivinanza3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbfallas3)
                    .addComponent(jlbAciertos3)
                    .addComponent(jlbintentos3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnResultadosA)
                    .addComponent(btnIniciar))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadosAActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void txtAdivinanzaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdivinanzaKeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtAdivinanzaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAvanzado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar;
    public javax.swing.JButton btnResultadosA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jlbAciertos;
    public javax.swing.JLabel jlbAciertos1;
    public javax.swing.JLabel jlbAciertos2;
    public javax.swing.JLabel jlbAciertos3;
    public javax.swing.JLabel jlbPalabra1;
    public javax.swing.JLabel jlbPalabra2;
    public javax.swing.JLabel jlbPalabra3;
    public javax.swing.JLabel jlbfallas;
    public javax.swing.JLabel jlbfallas1;
    public javax.swing.JLabel jlbfallas2;
    public javax.swing.JLabel jlbfallas3;
    public javax.swing.JLabel jlbintentos;
    public javax.swing.JLabel jlbintentos1;
    public javax.swing.JLabel jlbintentos2;
    public javax.swing.JLabel jlbintentos3;
    public javax.swing.JTextField txtAdivinanza;
    public javax.swing.JTextField txtAdivinanza1;
    public javax.swing.JTextField txtAdivinanza2;
    public javax.swing.JTextField txtAdivinanza3;
    // End of variables declaration//GEN-END:variables
}
