/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class FrmPrincipiante extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipiante
     */
    public FrmPrincipiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbSuma1 = new javax.swing.JLabel();
        jlbSuma2 = new javax.swing.JLabel();
        txtSuma2 = new javax.swing.JTextField();
        btnResultadosP = new javax.swing.JButton();
        btnNivelP = new javax.swing.JButton();
        btnActivar = new javax.swing.JButton();
        jlbAciertos = new javax.swing.JLabel();
        jlbfallas = new javax.swing.JLabel();
        jlbintentos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbNo1 = new javax.swing.JLabel();
        jlbAciertos1 = new javax.swing.JLabel();
        jlbNo2 = new javax.swing.JLabel();
        jlbfallas1 = new javax.swing.JLabel();
        jlbintentos1 = new javax.swing.JLabel();
        txtResultado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbNo3 = new javax.swing.JLabel();
        jlbAciertos2 = new javax.swing.JLabel();
        jlbNo4 = new javax.swing.JLabel();
        jlbfallas2 = new javax.swing.JLabel();
        jlbintentos2 = new javax.swing.JLabel();
        txtResultado3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlbintentos3 = new javax.swing.JLabel();
        txtResultado4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlbNo5 = new javax.swing.JLabel();
        jlbAciertos3 = new javax.swing.JLabel();
        jlbNo6 = new javax.swing.JLabel();
        jlbfallas3 = new javax.swing.JLabel();
        jlbNo7 = new javax.swing.JLabel();
        jlbAciertos4 = new javax.swing.JLabel();
        jlbNo8 = new javax.swing.JLabel();
        jlbfallas4 = new javax.swing.JLabel();
        jlbintentos4 = new javax.swing.JLabel();
        txtResta1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jlbintentos5 = new javax.swing.JLabel();
        txtResta2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jlbNo9 = new javax.swing.JLabel();
        jlbAciertos5 = new javax.swing.JLabel();
        jlbNo10 = new javax.swing.JLabel();
        jlbfallas5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlbSuma1.setText("#1");

        jlbSuma2.setText("#2");

        txtSuma2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSuma2KeyTyped(evt);
            }
        });

        btnResultadosP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/resultados-de-la-votacion.png"))); // NOI18N
        btnResultadosP.setText("Comprobar");
        btnResultadosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosPActionPerformed(evt);
            }
        });

        btnNivelP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/subir-de-nivel.png"))); // NOI18N
        btnNivelP.setText("Siguiente Nivel");

        btnActivar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comienzo.png"))); // NOI18N
        btnActivar.setText("Empezar");
        btnActivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarActionPerformed(evt);
            }
        });

        jlbAciertos.setText("0");

        jlbfallas.setText("0");

        jlbintentos.setText("0");

        jLabel1.setText("Aciertos");

        jLabel2.setText("fallas");

        jLabel3.setText("intentos");

        jlbNo1.setText("#1");

        jlbAciertos1.setText("0");

        jlbNo2.setText("#2");

        jlbfallas1.setText("0");

        jlbintentos1.setText("0");

        txtResultado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado2KeyTyped(evt);
            }
        });

        jLabel4.setText("+");

        jLabel5.setText("+");

        jLabel6.setText("Ingrese sus respuestas");

        jlbNo3.setText("#1");

        jlbAciertos2.setText("0");

        jlbNo4.setText("#2");

        jlbfallas2.setText("0");

        jlbintentos2.setText("0");

        txtResultado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado3KeyTyped(evt);
            }
        });

        jLabel7.setText("*");

        jlbintentos3.setText("0");

        txtResultado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResultado4KeyTyped(evt);
            }
        });

        jLabel8.setText("/");

        jlbNo5.setText("#1");

        jlbAciertos3.setText("0");

        jlbNo6.setText("#2");

        jlbfallas3.setText("0");

        jlbNo7.setText("#1");

        jlbAciertos4.setText("0");

        jlbNo8.setText("#2");

        jlbfallas4.setText("0");

        jlbintentos4.setText("0");

        txtResta1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResta1KeyTyped(evt);
            }
        });

        jLabel9.setText("-");

        jlbintentos5.setText("0");

        txtResta2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtResta2KeyTyped(evt);
            }
        });

        jLabel10.setText("-");

        jlbNo9.setText("#1");

        jlbAciertos5.setText("0");

        jlbNo10.setText("#2");

        jlbfallas5.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbSuma1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbSuma2))
                            .addComponent(btnActivar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNo4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNo5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNo6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNo2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnResultadosP)
                                .addGap(18, 18, 18)
                                .addComponent(btnNivelP)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtResultado3, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                        .addComponent(txtResultado4)
                                        .addComponent(txtResta1, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtSuma2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtResta2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jlbAciertos3)
                                            .addComponent(jlbAciertos)
                                            .addComponent(jlbAciertos1)
                                            .addComponent(jlbAciertos2)
                                            .addComponent(jlbAciertos5)
                                            .addComponent(jlbAciertos4))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(jlbfallas)
                                                .addGap(28, 28, 28)
                                                .addComponent(jlbintentos))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jlbfallas3)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jlbintentos3))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jlbfallas1)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jlbintentos1))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(jlbfallas2)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jlbintentos2))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jlbfallas4)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jlbintentos4))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jlbfallas5)
                                                        .addGap(28, 28, 28)
                                                        .addComponent(jlbintentos5)))))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNo9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNo10))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbNo7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNo8)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel6))
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbfallas)
                            .addComponent(jlbintentos))
                        .addGap(102, 102, 102)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbfallas3)
                            .addComponent(jlbintentos3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbSuma1)
                            .addComponent(jlbSuma2)
                            .addComponent(jLabel4)
                            .addComponent(txtSuma2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbNo1)
                            .addComponent(jlbNo2)
                            .addComponent(jLabel5)
                            .addComponent(txtResultado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo3)
                                    .addComponent(jlbNo4)
                                    .addComponent(jLabel7))
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(txtResultado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo5)
                                    .addComponent(jlbNo6)
                                    .addComponent(jLabel8)))
                            .addComponent(txtResultado4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbNo7)
                                .addComponent(jlbNo8)
                                .addComponent(jLabel9))
                            .addComponent(txtResta1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlbNo9)
                                    .addComponent(jlbNo10)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtResta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbintentos2)
                                        .addComponent(jlbfallas2))
                                    .addComponent(jlbAciertos2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlbAciertos)
                                .addGap(19, 19, 19)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbintentos1)
                                        .addComponent(jlbfallas1))
                                    .addComponent(jlbAciertos1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jlbAciertos3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbfallas5)
                                        .addComponent(jlbintentos5))
                                    .addComponent(jlbAciertos5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jlbintentos4)
                                        .addComponent(jlbfallas4))
                                    .addComponent(jlbAciertos4))
                                .addGap(38, 38, 38)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActivar)
                    .addComponent(btnResultadosP)
                    .addComponent(btnNivelP))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResultadosPActionPerformed

    private void btnActivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnActivarActionPerformed

    private void txtSuma2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuma2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtSuma2KeyTyped

    private void txtResultado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado2KeyTyped

    private void txtResultado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado3KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado3KeyTyped

    private void txtResultado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResultado4KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResultado4KeyTyped

    private void txtResta1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResta1KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResta1KeyTyped

    private void txtResta2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResta2KeyTyped
        // TODO add your handling code here:
        char validar = evt.getKeyChar();

        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Campo solo para numeros");
        }
    }//GEN-LAST:event_txtResta2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActivar;
    public javax.swing.JButton btnNivelP;
    public javax.swing.JButton btnResultadosP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jlbAciertos;
    public javax.swing.JLabel jlbAciertos1;
    public javax.swing.JLabel jlbAciertos2;
    public javax.swing.JLabel jlbAciertos3;
    public javax.swing.JLabel jlbAciertos4;
    public javax.swing.JLabel jlbAciertos5;
    public javax.swing.JLabel jlbNo1;
    public javax.swing.JLabel jlbNo10;
    public javax.swing.JLabel jlbNo2;
    public javax.swing.JLabel jlbNo3;
    public javax.swing.JLabel jlbNo4;
    public javax.swing.JLabel jlbNo5;
    public javax.swing.JLabel jlbNo6;
    public javax.swing.JLabel jlbNo7;
    public javax.swing.JLabel jlbNo8;
    public javax.swing.JLabel jlbNo9;
    public javax.swing.JLabel jlbSuma1;
    public javax.swing.JLabel jlbSuma2;
    public javax.swing.JLabel jlbfallas;
    public javax.swing.JLabel jlbfallas1;
    public javax.swing.JLabel jlbfallas2;
    public javax.swing.JLabel jlbfallas3;
    public javax.swing.JLabel jlbfallas4;
    public javax.swing.JLabel jlbfallas5;
    public javax.swing.JLabel jlbintentos;
    public javax.swing.JLabel jlbintentos1;
    public javax.swing.JLabel jlbintentos2;
    public javax.swing.JLabel jlbintentos3;
    public javax.swing.JLabel jlbintentos4;
    public javax.swing.JLabel jlbintentos5;
    public javax.swing.JTextField txtResta1;
    public javax.swing.JTextField txtResta2;
    public javax.swing.JTextField txtResultado2;
    public javax.swing.JTextField txtResultado3;
    public javax.swing.JTextField txtResultado4;
    public javax.swing.JTextField txtSuma2;
    // End of variables declaration//GEN-END:variables
}
